debug: false
store-url: https://store.example.com
weblistener:
  secret-enabled: true
  secret-key: 1234567890
auth:
  timeout: 300
  initial-message: "<dark_green>You are trying to log in to our </dark_green><gold><bold>store. CLICK HERE </bold><dark_green>to confirm authorization! If you are not able to click run /minestore auth.</dark_green>"
  success-message: "<dark_green>You have successfully logged in to our store!</dark_green>"
  failure-message: "<dark_red>You have failed to log in to our store!</dark_red>"